import ReusableCarousel from "@/components/ReusableCarousel";
import React from "react";

const item = [
  {
    id: "1",
    src: "/imgs/controlsystem/f1.png",
    alt: "HDMI TO SDI",
    title: "HDMI TO SDI",
    description: "AV MATRIX SC1221",
    link: "/controlsystem/1",
  },
  {
    id: "2",
    src: "/imgs/controlsystem/f2.png",
    alt: "SDI TO HDMI",
    title: "SDI TO HDMI",
    description: "AV MATRIX 1112",
    link: "/controlsystem/2",
  },
  {
    id: "3",
    src: "/imgs/controlsystem/f3.png",
    alt: "SDI SPLITTER",
    title: "SDI SPLITTER",
    description: "AV MATRIX 3G SDI 4X1",
    link: "/controlsystem/3",
  },
  {
    id: "4",
    src: "/imgs/controlsystem/f4.png",
    alt: "CAPTURE CARD",
    title: "CAPTURE CARD",
    description: "BLACKMAGIC MINI RECORDER",
    link: "/controlsystem/4",
  },
  {
    id: "5",
    src: "/imgs/controlsystem/f5.png",
    alt: "CAPTURE CARD",
    title: "CAPTURE CARD",
    description: "BLACKMAGIC MINI MONITOR",
    link: "/controlsystem/5",
  },
  {
    id: "6",
    src: "/imgs/controlsystem/f6.jpeg",
    alt: "CAPTURE CARD",
    title: "CAPTURE CARD",
    description: "AVERMEDIA 4K CAPTURE CARD",
    link: "/controlsystem/6",
  },
  {
    id: "7",
    src: "/imgs/controlsystem/f7.jpeg",
    alt: "PROJECTOR",
    title: "PROJECTOR",
    description: "EPSON EF 100 LASER PROJECTOR",
    link: "/controlsystem/7",
  },
  {
    id: "8",
    src: "/imgs/controlsystem/f8.jpeg",
    alt: "MONITOR",
    title: "MONITOR",
    description: "ATMOS SHINOBI",
    link: "/controlsystem/8",
  },
  {
    id: "9",
    src: "/imgs/controlsystem/f9.jpeg",
    alt: "MONITOR",
    title: "MONITOR",
    description: "DELL 24inc TOUCH MONITOR ",
    link: "/controlsystem/9",
  },
  {
    id: "10",
    src: "/imgs/controlsystem/f10.jpeg",
    alt: "MONITOR",
    title: "MONITOR",
    description: "DELL 24-27inc MONITOR",
    link: "/controlsystem/10",
  },
  {
    id: "11",
    src: "/imgs/controlsystem/f11.jpeg",
    alt: "HDMI OVER ETHERNET",
    title: "HDMI OVER ETHERNET",
    description: "ATLONA HDMI OVER CAT6",
    link: "/controlsystem/11",
  },
  {
    id: "12",
    src: "/imgs/controlsystem/f12.jpeg",
    alt: "MINIMAD",
    title: "MINIMAD",
    description: "MAD MAPPER MINI MAD",
    link: "/controlsystem/12",
  },
  {
    id: "13",
    src: "/imgs/controlsystem/f13.jpeg",
    alt: "ACTIVE SPEAKER",
    title: "ACTIVE SPEAKER",
    description: "QUEST QSA-200l",
    link: "/controlsystem/13",
  },
  {
    id: "14",
    src: "/imgs/controlsystem/f14.jpeg",
    alt: "ACTIVE SPEAKER",
    title: "ACTIVE SPEAKER",
    description: "YAMAHA DXR 8",
    link: "/controlsystem/14",
  },
  {
    id: "15",
    src: "/imgs/controlsystem/f15.jpeg",
    alt: "OUTDOOR SPEAKER",
    title: "OUTDOOR SPEAKER",
    description: "YAMAHA 8inc OUTDOOR PASSIVE",
    link: "/controlsystem/15",
  },
  {
    id: "16",
    src: "/imgs/controlsystem/f16.jpeg",
    alt: "MICROPHONE",
    title: "MICROPHONE",
    description: "SHURE SM58",
    link: "/controlsystem/16",
  },
  {
    id: "17",
    src: "/imgs/controlsystem/f17.jpeg",
    alt: "MICROPHONE",
    title: "MICROPHONE",
    description: "RODE CONDENSER",
    link: "/controlsystem/17",
  },
  {
    id: "18",
    src: "/imgs/controlsystem/f18.jpeg",
    alt: "IEM SYSTEM",
    title: "IEM SYSTEM",
    description: "SENNHEISER G4",
    link: "/controlsystem/18",
  },
  {
    id: "19",
    src: "/imgs/controlsystem/f19.jpeg",
    alt: "IEM SYSTEM",
    title: "BATTERY FAN",
    description: "BEHRINGER P2",
    link: "/controlsystem/19",
  },
  {
    id: "20",
    src: "/imgs/controlsystem/f20.jpeg",
    alt: "MIXER",
    title: "MIXER",
    description: "BEHRINGER XAIR 12",
    link: "/controlsystem/20",
  },
  {
    id: "21",
    src: "/imgs/controlsystem/f21.jpeg",
    alt: "MIXER",
    title: "MIXER",
    description: "MACKIE MIX 5",
    link: "/controlsystem/21",
  },
  {
    id: "22",
    src: "/imgs/controlsystem/f22.jpeg",
    alt: "AUDIO INTERFACE",
    title: "AUDIO INTERFACE",
    description: "FOCUSRITE SCARLET SOLO",
    link: "/controlsystem/22",
  },
  {
    id: "23",
    src: "/imgs/controlsystem/f23.jpeg",
    alt: "AUDIO INTERFACE",
    title: "AUDIO INTERFACE",
    description: "FOCUSRITE SCARLET 18l20",
    link: "/controlsystem/23",
  },
  {
    id: "24",
    src: "/imgs/controlsystem/f24.jpeg",
    alt: "WIRELESS INTERCOM",
    title: "WIRELESS INTERCOM",
    description: "HOLLYLAND MARS KIT",
    link: "/controlsystem/24",
  },
  {
    id: "25",
    src: "/imgs/controlsystem/f25.jpeg",
    alt: "WIRELESS INTERCOM",
    title: "WIRELESS INTERCOM",
    description: "HOLLYLAND MARS KIT",
    link: "/controlsystem/25",
  },
  {
    id: "26",
    src: "/imgs/controlsystem/f26.jpeg",
    alt: "ARNET NODE",
    title: "ARNET NODE",
    description: "ACME A28 ARNET NODE",
    link: "/controlsystem/26",
  },
  {
    id: "27",
    src: "/imgs/controlsystem/f27.jpeg",
    alt: "ARNET NODE",
    title: "ARNET NODE",
    description: "DMX KING ARNET NODE",
    link: "/controlsystem/27",
  },
  {
    id: "28",
    src: "/imgs/controlsystem/f28.jpeg",
    alt: "DMX SPLITTER",
    title: "DMX SPLITTER",
    description: "ENTTEC D-SPLITT",
    link: "/controlsystem/28",
  },
  {
    id: "29",
    src: "/imgs/controlsystem/f29.jpeg",
    alt: "DMX SPLITTER",
    title: "DMX SPLITTER",
    description: "LIGHTSKY DMX SPLITTER 2 UNIVERSE",
    link: "/controlsystem/29",
  },
  {
    id: "30",
    src: "/imgs/controlsystem/f30.jpeg",
    alt: "DMX SPLITTER",
    title: "DMX SPLITTER",
    description: "DMX SPLITTER 1 UNIVERSE",
    link: "/controlsystem/30",
  },
  {
    id: "31",
    src: "/imgs/controlsystem/f31.jpeg",
    alt: "DMX DIMMER",
    title: "DMX DIMMER",
    description: "ELATION MONO PACK",
    link: "/controlsystem/31",
  },
];

const ControlSystem = () => {
  return (
    <main className="flex flex-col h-fit px-10 w-full">
      <h1 className="text-5xl font-extrabold my-4 pt-10 px-10 pb-8 items-start">
        CONTROL SYSTEM
      </h1>
      <ReusableCarousel items={item} />
    </main>
  );
};

export default ControlSystem;
